config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'splash#index'

  resources :groups do
    resources :exchanges
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user || User.new

    can :manage, Group
    can :manage, Exchange
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category_exchange.rb
class CategoryExchange < ApplicationRecord
  belongs_to :group
  belongs_to :exchange
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  has_many :category_exchanges, foreign_key: 'exchange_id'

  validates :name, presence: true
  validates :amount, numericality: { only_decimal: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :category_exchanges, foreign_key: 'group_id'

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :exchanges, foreign_key: 'user_id'
  has_many :groups, foreign_key: 'user_id'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :authenticate_user!

  def new
    @transanction = Exchange.new
    @current_user = current_user
    @category_map = @current_user.groups.pluck(:name, :id)
  end

  def create
    new_transanction = Exchange.new(transanction_params)
    new_transanction.user = current_user
    respond_to do |format|
      if new_transanction.save
        group = Group.find_by(id: params[:category])
        CategoryExchange.create(group:, exchange: new_transanction)
        format.html { redirect_to group_path(id: group.id), notice: 'Transanction was successfully created.' }
        format.json { render :index, status: :created, location: new_transanction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transanction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def transanction_params
    params.require(:exchange).permit(:name, :amount, user: current_user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.groups
    @current_user = current_user
    @total = CategoryExchange
    @categories_total = 0
  end

  def show
    @groups = current_user.groups.includes(category_exchanges: :exchange).find_by(id: params[:id])
    @categories = @groups.category_exchanges.order('created_at DESC')
    @categories_total = 0
  end

  def new
    @category = Group.new
    @current_user = current_user
  end

  def create
    new_category = Group.new(category_params)
    new_category.user = current_user
    respond_to do |format|
      if new_category.save
        format.html { redirect_to '/groups', notice: 'Category was successfully created.' }
        format.json { render :index, status: :created, location: new_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def category_params
    params.require(:group).permit(:name, :icon, user: current_user)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/exchanges/new.html.erb
<% if user_signed_in? %>
      <a class="back-button" href="/">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" id="backe" height="16" fill="currentColor" class="bi bi-arrow-left arrow" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
    </svg>
    </a>
  <div class="">
  <h1 class="new-category-heading">New transanction</h1>
  <% if @transanction.errors.any? %>
    <div class="post-errors-box">
      <p><%= pluralize(@transanction.errors.count, "error") %> found:</p>

      <ul class="post-errors-ul">
        <% @transanction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_with url: group_exchanges_path , model: @transanction , class: 'new-category' do |form| %>
    <div class="input-div field">
      <%= form.text_field :name, required: true, class: 'input-field', placeholder: 'Name' %>
    </div>
    <div class="input-div field">
      <%= form.number_field :amount, required: true, class: 'input-field', placeholder: 'Amount' %>
    </div>
    <div class="input-div select-tag field">
     <%= select_tag(:category, options_for_select(current_user.groups.map { |category| [category.name, category.id] })) %>
  </div>
    <div class="submit-button actions">
      <%= form.submit "Save", class: 'splash-second-link'%>
    </div>
  <% end %>
</div>
<% else %>
  <p>Please, sign in to create a transanction item</p>
<% end %>

app/views/groups/index.html.erb
<header>
<h1 class="new-category-heading"><b>Categories</b></h1>
</header>
<% if @categories.empty? %>
  <h2>There is no categories for now</h2>
<% end %>
<div >
    <ul class="categories-list">
        <% @categories.each do |category| %>
          <li class="my-6">
            <% @amount = 0%>
          <img src=<%=category.icon%> class="images"  alt="Girl in a jacket" width="80" height="80">
          <% @total.where(group: category).each do | item | %>
          <% @amount += item.exchange.amount %>
          <% end %>
          <%= link_to category.name, "/groups/#{category.id}" %>
          <p> $<%= @amount%></p>
          </li>
        <% end %>
    </ul>
</div>
<div class="new-category button-div">
  <%= link_to 'Add New Category', new_group_path %>
</div>

app/views/groups/new.html.erb
<% if user_signed_in? %>
    <a class="back-button" href="/groups">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left arrow" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
    </svg>
    </a>
  <div>
  <h1 class="new-category-heading">New Category</h1>
  <% if @category.errors.any? %>
    <div class="post-errors-box">
      <p><%= pluralize(@category.errors.count, "error") %> found:</p>

      <ul class="post-errors-ul">
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with url: "/groups", model: @category, class: 'new-category' do |form| %>
    <div class="input-div field">
      <%= form.text_field :name, required: true, class: 'input-field', placeholder: 'Name'  %>
    </div>
    <div class="input-div field">
      <%= form.text_field :icon, required: true, class: 'input-field', placeholder: 'Icon URL' %>
    </div>
    <div class="submit-button actions">
      <%= form.submit "Save", class: 'splash-second-link'%>
    </div>
  <% end %>
</div>
<% else %>
  <p>Please, sign in to create a category item</p>
<% end %>

app/views/groups/show.html.erb
<a class="back-button" href="/groups">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left arrow" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
  </svg>
</a>

<h1 class='new-category-heading'>Transanctions</h1>
<% if @categories.empty? %>
  <h2 class="text-center">There is no transanction for now</h2>
<% end %>
<div class="w-10/12 mx-auto">
    <ul class="transanction-list">
       <% @categories.each do |category| %>
        <% @categories_total += category.exchange.amount%>
       <%end %>
       <p>Total Amount $<%= @categories_total %></p>
        <% @categories.each do |category| %>
          <li class="">
          <p><%= category.exchange.name %></p>
           <p class="amount">$<%= category.exchange.amount %></p>
            <p><%= category.exchange.created_at %></p>
          </li>
        <% end %>
    </ul>
</div>

<div class="new-category">
  <%= link_to 'Add New Transanction', new_group_exchange_path(@groups.id) , class: "px-4 py-2 border-2 border-black cursor:pointer" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splash">
    <div class="splash-first">
        <h1 class="splash-first-title">Budget App</h1>
    </div>
    <div class="splash-second">
        <p class="splash-second-link"><%= link_to "LOG IN" ,  groups_path	%></p>
        <p class="splash-third-link"><%= link_to "SIGN UP" , new_user_registration_path %></p>
    </div>
</div>